"""
Django settings for tag_rugby_manager project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

<<<<<<< HEAD
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
=======
ALLOWED_HOSTS = [".herokuapp.com", "127.0.0.1"]

>>>>>>> 7c03a2b3f635122bb16c4c7b8ae7ab258b76ddec

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
<<<<<<< HEAD
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # Local apps
    "accounts",
    "core",
    "seasons",
    "teams",
    "fixtures",
    "standings",
]

SITE_ID = 1  # required for multi-site support
LOGIN_REDIRECT_URL = "/"  # redirect here after login
LOGOUT_REDIRECT_URL = "/"  # redirect here after logout

=======
    "accounts",
]

>>>>>>> 7c03a2b3f635122bb16c4c7b8ae7ab258b76ddec
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
<<<<<<< HEAD
    "allauth.account.middleware.AccountMiddleware",
=======
>>>>>>> 7c03a2b3f635122bb16c4c7b8ae7ab258b76ddec
]

ROOT_URLCONF = "tag_rugby_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tag_rugby_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

<<<<<<< HEAD
ACCOUNT_EMAIL_VERIFICATION = "none"
=======
>>>>>>> 7c03a2b3f635122bb16c4c7b8ae7ab258b76ddec

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = "accounts.User"
<<<<<<< HEAD

ACCOUNT_ADAPTER = "accounts.adapters.CustomAccountAdapter"
=======
>>>>>>> 7c03a2b3f635122bb16c4c7b8ae7ab258b76ddec
