# Generated by Django 4.2.29 on 2026-04-22 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestregistration',
            name='estimated_players',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='female_players',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='is_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='male_players',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='played_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestregistration',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
