# Generated by Django 4.2.29 on 2026-04-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interestregistration_estimated_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailwhitelist',
            name='team',
        ),
        migrations.AddField(
            model_name='emailwhitelist',
            name='interest_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interestregistration'),
        ),
    ]
