# Generated by Django 4.2.29 on 2026-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
    ]
