# Generated by Django 6.0.4 on 2026-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_rename_seasons_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
