# Generated by Django 6.0.4 on 2026-04-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_alter_season_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='num_pitches',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='season',
            name='num_rounds',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='SeasonTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='seasons.season')),
            ],
            options={
                'ordering': ['order', 'time'],
                'unique_together': {('season', 'time')},
            },
        ),
    ]
