# Generated by Django 6.0.4 on 2026-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_season_num_pitches_season_num_rounds_seasontimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='venue',
            field=models.CharField(choices=[('irishtown', 'Irishtown Stadium, Dublin'), ('ballsbridge', 'Pembroke Wanders, Dublin'), ('ucd', 'UCD (Devlin GAA), Dublin'), ('sandymount', 'Pembroke Cricket Club, Dublin'), ('clontarf', 'Clontarf Road Astro Pitches, Dublin'), ('drumcondra', 'Belvedere Rugby Grounds, Dublin'), ('grangegorman', 'TUD Grangegorman, Dublin')], max_length=200),
        ),
    ]
