# Generated by Django 4.2.29 on 2026-04-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_remove_team_approved_team_status'),
        ('seasons', '0004_alter_season_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
    ]
