# Generated by Django 4.2.29 on 2026-04-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0004_alter_season_venue'),
        ('teams', '0002_remove_team_approved_team_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('team_a_score', models.IntegerField(blank=True, null=True)),
                ('team_b_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('played', 'Played'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='teams.team')),
            ],
        ),
    ]
