# Generated by Django 4.2.29 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('semi_final', 'Semi Final'), ('third_place', 'Third Place'), ('final', 'Final')], default='regular', max_length=20),
        ),
    ]
