# Generated by Django 4.2.29 on 2026-04-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_approved_team_status'),
        ('fixtures', '0002_match_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='teams.team'),
        ),
    ]
