# Generated by Django 6.0.4 on 2026-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_remove_match_venue_alter_match_round_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pitch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
