# Generated by Django 6.0.4 on 2026-05-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_match_pitch'),
        ('teams', '0003_alter_team_id_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='fixtures.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teams.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
